from __future__ import annotations

from .acquisition import (
    AcquisitionCandidate,
    AcquisitionPlan,
    local_readiness_for_record,
    plan_acquisition,
    plan_inventory_acquisition,
    summarize_acquisition_plans,
)
from .audit import ActionAuditLog, AuditEvent, DryRunActionSink
from .control import ControlAction, ControlRouter, IntentCommand
from .datasets import DatasetInventory, DatasetRecord, load_eeg_dataset_inventory
from .exercise import DatasetExerciseRecord, exercise_dataset_records, summarize_dataset_exercise
from .frame import Channel, Event, FrameValidationError, NeuroFrame, Timebase, ValidityIssue
from .kernels import Bandpass, ReReference, Resample, SpectralFeatures, ValidateEEG
from .loaders import (
    can_load_extension,
    load,
    load_csv,
    load_directory,
    load_hdf5,
    load_mat,
    load_mne_raw,
    load_nwb,
    load_numpy,
    load_parquet,
    load_pickle,
    load_r,
    load_spreadsheet,
    load_torch,
    load_xdf,
    find_supported_signal_files,
    supported_extensions,
)
from .materialization import (
    ArchiveExtractionResult,
    MaterializationResult,
    RemoteFileCandidate,
    RemoteFileResolution,
    extract_supported_signal_files_from_archive,
    materialize_remote_file,
    materialize_remote_files,
    resolve_inventory_remote_files,
    resolve_remote_files,
    summarize_remote_file_resolutions,
)
from .pipeline import Pipeline, PipelineExecutionError, PipelineReport, PipelineResult
from .quality import SignalQualityReport, score_signal_quality
from .settings import NeuroCoreSettings
from .stream import StreamBuffer, StreamWindow

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "AcquisitionCandidate",
    "AcquisitionPlan",
    "ActionAuditLog",
    "ArchiveExtractionResult",
    "AuditEvent",
    "Bandpass",
    "Channel",
    "ControlAction",
    "ControlRouter",
    "DatasetInventory",
    "DatasetExerciseRecord",
    "DatasetRecord",
    "DryRunActionSink",
    "Event",
    "FrameValidationError",
    "IntentCommand",
    "MaterializationResult",
    "NeuroCoreSettings",
    "NeuroFrame",
    "Pipeline",
    "PipelineExecutionError",
    "PipelineReport",
    "PipelineResult",
    "RemoteFileCandidate",
    "RemoteFileResolution",
    "ReReference",
    "Resample",
    "SignalQualityReport",
    "SpectralFeatures",
    "StreamBuffer",
    "StreamWindow",
    "Timebase",
    "ValidateEEG",
    "ValidityIssue",
    "load",
    "load_csv",
    "load_directory",
    "load_eeg_dataset_inventory",
    "load_hdf5",
    "load_mat",
    "load_mne_raw",
    "load_nwb",
    "load_numpy",
    "load_parquet",
    "load_pickle",
    "load_r",
    "load_spreadsheet",
    "load_torch",
    "load_xdf",
    "extract_supported_signal_files_from_archive",
    "exercise_dataset_records",
    "materialize_remote_file",
    "materialize_remote_files",
    "find_supported_signal_files",
    "local_readiness_for_record",
    "plan_acquisition",
    "plan_inventory_acquisition",
    "resolve_inventory_remote_files",
    "resolve_remote_files",
    "score_signal_quality",
    "summarize_acquisition_plans",
    "summarize_dataset_exercise",
    "summarize_remote_file_resolutions",
    "can_load_extension",
    "supported_extensions",
]
